In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stat

In [2]:
import torch as T
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [14]:
import keras as K
from keras.layers import Input, Dense
from keras.models import Model

In [6]:
layer = nn.Linear(5, 10)

In [8]:
list(layer.parameters())

[Parameter containing:
 tensor([[ 0.0573,  0.3235,  0.1096,  0.2283,  0.3479],
         [ 0.1974,  0.0226,  0.3953, -0.1411,  0.2091],
         [-0.2569, -0.2003,  0.3738,  0.4228,  0.0897],
         [-0.0276,  0.3430, -0.1228,  0.3022, -0.1704],
         [-0.1291, -0.4137, -0.0901, -0.1891, -0.4353],
         [ 0.0270,  0.4180,  0.4233, -0.4339,  0.0609],
         [-0.3881, -0.3883,  0.3954, -0.2417,  0.1240],
         [-0.4169, -0.3187,  0.3027,  0.2376, -0.0362],
         [ 0.3118, -0.1549, -0.1227,  0.0920,  0.4161],
         [ 0.2448,  0.2855, -0.3704, -0.0101, -0.4267]]), Parameter containing:
 tensor([-0.0580,  0.0539, -0.1297, -0.3654, -0.4319, -0.4127, -0.2834,
         -0.1174,  0.4213, -0.4226])]

In [9]:
dir(layer)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__format__',
 '__getattr__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_all_buffers',
 '_apply',
 '_backend',
 '_backward_hooks',
 '_buffers',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_name',
 '_load_from_state_dict',
 '_modules',
 '_parameters',
 '_slow_forward',
 '_tracing_name',
 '_version',
 'add_module',
 'apply',
 'bias',
 'children',
 'cpu',
 'cuda',
 'double',
 'dump_patches',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'half',
 'in_features',
 'load_state_dict',
 'modules',
 'named_children',
 'named_modules',
 'named_parameters',
 'out_features',
 'parameters',
 'register_backward_hook',
 'register_buffer',
 'register_forward_hook',
 'register_forward_pre_hook',
 'register_parameter',
 'reset_parameters',
 'shar

In [13]:
layer.weight

Parameter containing:
tensor([[ 0.0573,  0.3235,  0.1096,  0.2283,  0.3479],
        [ 0.1974,  0.0226,  0.3953, -0.1411,  0.2091],
        [-0.2569, -0.2003,  0.3738,  0.4228,  0.0897],
        [-0.0276,  0.3430, -0.1228,  0.3022, -0.1704],
        [-0.1291, -0.4137, -0.0901, -0.1891, -0.4353],
        [ 0.0270,  0.4180,  0.4233, -0.4339,  0.0609],
        [-0.3881, -0.3883,  0.3954, -0.2417,  0.1240],
        [-0.4169, -0.3187,  0.3027,  0.2376, -0.0362],
        [ 0.3118, -0.1549, -0.1227,  0.0920,  0.4161],
        [ 0.2448,  0.2855, -0.3704, -0.0101, -0.4267]])

In [ ]:
Dense(1)