In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stat

In [2]:
import torch as T
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [15]:
import keras as K
import keras.layers as KL
import keras.models as KM

In [17]:
H = W = 28
enc = KM.Sequential()
enc.add(KL.Conv2D(16, (3, 3), activation="relu", padding="same",
input_shape=(H, W, 1)))
enc.add(KL.MaxPooling2D((2, 2), padding="same"))
enc.add(KL.Conv2D(8, (3, 3), activation="relu", padding="same"))
enc.add(KL.MaxPooling2D((2, 2), padding="same"))
enc.add(KL.Conv2D(8, (3, 3), activation="relu", padding="same"))
enc.add(KL.MaxPooling2D((2, 2), padding="same"))
enc.layers[-1].output_shape

(None, 4, 4, 8)

In [30]:
seq = KM.Sequential()
seq.add(KL.Dense(10, input_shape=(10,)))
seq.layers[0].output_shape

(None, 10)

In [45]:
x = T.randn(100,28,28)
x.unsqueeze(3).shape

torch.Size([100, 28, 28, 1])

In [46]:
c = nn.Conv2d(1, 16, 3, padding=1)

In [53]:
len(list(c.parameters()))

2

In [58]:
N, H, W, C = shape = (100, 9, 16, 3)
x = T.randn(*shape)
x.permute(0,3,1,2).shape

torch.Size([100, 3, 9, 16])

In [67]:
x.view(x.size(0),-1).shape

torch.Size([100, 432])

In [64]:
np.random.randn(*shape).mean(axis=(1,2,3))

array([-0.03128077, -0.03140585, -0.03711113, -0.03376895,  0.00679265,
        0.07929957, -0.03560515, -0.01639745,  0.00513535, -0.03514862,
        0.01214435,  0.03809296, -0.04939611, -0.01014966, -0.01141113,
        0.05275601, -0.11835978,  0.00104154,  0.02069406,  0.01723971,
       -0.02590562, -0.02217248,  0.1149882 ,  0.09371392,  0.01756015,
        0.03562615,  0.03454905,  0.03372058, -0.03395695,  0.04372535,
       -0.01398423,  0.06773129, -0.02385572, -0.08826905,  0.0351416 ,
        0.00820814,  0.00754348, -0.0866015 ,  0.0070538 , -0.0322756 ,
       -0.0079617 ,  0.04043268,  0.05499927, -0.01727202,  0.03432511,
        0.0692946 ,  0.01672833, -0.00609648,  0.03495277, -0.03003597,
        0.09695362, -0.02153637, -0.02725231,  0.01253891, -0.03463025,
        0.00286305, -0.0222347 , -0.05259975,  0.04361466, -0.00577727,
        0.10136186,  0.02847631, -0.0156172 , -0.01082244, -0.0203407 ,
        0.01461098, -0.00611476, -0.03060215, -0.0350413 ,  0.06

In [71]:
x = T.ones(2,2,2) + T.randn(2,2,2)
x

tensor([[[ 0.7966,  0.6701],
         [ 1.1672,  0.7463]],

        [[-0.0609,  1.6982],
         [ 1.0721,  3.1603]]])

In [72]:
x.clamp_(0,1)

tensor([[[ 0.7966,  0.6701],
         [ 1.0000,  0.7463]],

        [[ 0.0000,  1.0000],
         [ 1.0000,  1.0000]]])

In [73]:
T.ones((4, 5, 6)).randn().shape

AttributeError: 'Tensor' object has no attribute 'randn'

In [74]:
# t.randn_like(log_sigma).mul_((0.5*log_sigma).exp_()).add_(mu)
S = T.randn(5,5)
M = T.randn(5,5)

In [75]:
S, M

(tensor([[ 0.2346,  0.0387,  2.4075,  0.4174, -0.6153],
         [ 1.9141,  0.1388,  0.6303,  0.2822,  0.1745],
         [ 0.6830,  0.0112, -0.8546, -0.8576,  1.4736],
         [-1.9066,  0.3136,  1.1109, -0.1213,  0.0236],
         [-0.3291, -0.3856, -0.3412, -1.9049, -0.5645]]),
 tensor([[-0.5141, -0.6121,  0.6223,  0.0948,  0.2827],
         [-1.5340,  1.0838,  0.1655, -2.4982, -0.2128],
         [ 0.2984,  0.1590,  0.1693,  0.6040, -1.8696],
         [ 0.3916,  0.4016, -1.1077, -0.4135,  0.3196],
         [ 0.9521, -1.0119,  1.1728, -1.7679,  0.4394]]))

In [76]:
T.randn_like(S).mul_((0.5*S).exp_()).add_(M)

tensor([[-0.1056, -0.7452,  4.4939,  0.2895,  1.1320],
        [-2.0194,  2.2905, -0.2408, -2.8659, -2.0724],
        [-1.0927, -0.3211, -0.4285,  0.1085,  0.3718],
        [ 0.4798,  0.0778, -1.2579, -0.9094,  1.3348],
        [ 0.6015, -1.8260,  2.1360, -1.7654,  1.0876]])

In [77]:
S, M

(tensor([[ 0.2346,  0.0387,  2.4075,  0.4174, -0.6153],
         [ 1.9141,  0.1388,  0.6303,  0.2822,  0.1745],
         [ 0.6830,  0.0112, -0.8546, -0.8576,  1.4736],
         [-1.9066,  0.3136,  1.1109, -0.1213,  0.0236],
         [-0.3291, -0.3856, -0.3412, -1.9049, -0.5645]]),
 tensor([[-0.5141, -0.6121,  0.6223,  0.0948,  0.2827],
         [-1.5340,  1.0838,  0.1655, -2.4982, -0.2128],
         [ 0.2984,  0.1590,  0.1693,  0.6040, -1.8696],
         [ 0.3916,  0.4016, -1.1077, -0.4135,  0.3196],
         [ 0.9521, -1.0119,  1.1728, -1.7679,  0.4394]]))

In [82]:
x, y = T.rand(2, 6, 7, 8)

In [83]:
F.binary_cross_entropy(x, y, size_average=False)

tensor(358.3885)

In [84]:
F.binary_cross_entropy(x, y, reduce=False).sum()

tensor(358.3885)

In [87]:
x

tensor([[[ 0.9809,  0.9640,  0.6777,  0.6383,  0.3346,  0.7805,  0.0528,
           0.2286],
         [ 0.1237,  0.9896,  0.3023,  0.8594,  0.7110,  0.6426,  0.0320,
           0.7413],
         [ 0.1347,  0.6240,  0.9108,  0.6791,  0.4521,  0.8203,  0.5146,
           0.0509],
         [ 0.8184,  0.4085,  0.5172,  0.0950,  0.7101,  0.0600,  0.1392,
           0.6908],
         [ 0.8460,  0.1906,  0.4240,  0.6927,  0.0323,  0.7730,  0.8410,
           0.2109],
         [ 0.1930,  0.6140,  0.2046,  0.3310,  0.9203,  0.3139,  0.8127,
           0.2293],
         [ 0.3310,  0.7919,  0.4615,  0.5541,  0.1563,  0.6771,  0.0275,
           0.7224]],

        [[ 0.6739,  0.3479,  0.7164,  0.5972,  0.2427,  0.0098,  0.5110,
           0.8100],
         [ 0.1925,  0.7289,  0.0279,  0.5792,  0.2073,  0.2319,  0.1938,
           0.2870],
         [ 0.1260,  0.1665,  0.4861,  0.8576,  0.5848,  0.7644,  0.2159,
           0.9303],
         [ 0.2858,  0.2613,  0.8868,  0.5196,  0.7886,  0.3339,  0.7

In [86]:
x.add(1).sub_(1)

tensor([[[ 0.9809,  0.9640,  0.6777,  0.6383,  0.3346,  0.7805,  0.0528,
           0.2286],
         [ 0.1237,  0.9896,  0.3023,  0.8594,  0.7110,  0.6426,  0.0320,
           0.7413],
         [ 0.1347,  0.6240,  0.9108,  0.6791,  0.4521,  0.8203,  0.5146,
           0.0509],
         [ 0.8184,  0.4085,  0.5172,  0.0950,  0.7101,  0.0600,  0.1392,
           0.6908],
         [ 0.8460,  0.1906,  0.4240,  0.6927,  0.0323,  0.7730,  0.8410,
           0.2109],
         [ 0.1930,  0.6140,  0.2046,  0.3310,  0.9203,  0.3139,  0.8127,
           0.2293],
         [ 0.3310,  0.7919,  0.4615,  0.5541,  0.1563,  0.6771,  0.0275,
           0.7224]],

        [[ 0.6739,  0.3479,  0.7164,  0.5972,  0.2427,  0.0098,  0.5110,
           0.8100],
         [ 0.1925,  0.7289,  0.0279,  0.5792,  0.2073,  0.2319,  0.1938,
           0.2870],
         [ 0.1260,  0.1665,  0.4861,  0.8576,  0.5848,  0.7644,  0.2159,
           0.9303],
         [ 0.2858,  0.2613,  0.8868,  0.5196,  0.7886,  0.3339,  0.7

In [91]:
x.view(-1).shape

torch.Size([336])

In [94]:
T.randint(0, 256, (100,)).float()/255

tensor([ 0.6118,  0.0275,  0.3020,  0.5255,  0.7216,  0.8078,  0.1647,
         0.5451,  0.2431,  0.0588,  0.4196,  0.6353,  0.8980,  0.3216,
         0.6196,  0.5373,  0.6471,  0.2000,  0.1333,  0.6471,  0.0549,
         0.9137,  0.1373,  0.9412,  0.0157,  0.9451,  0.2118,  0.3137,
         0.2039,  0.5608,  0.3765,  0.4745,  0.2824,  0.7882,  0.2157,
         0.0000,  0.5804,  0.8902,  0.2784,  0.3882,  0.4157,  0.9804,
         0.9765,  0.1608,  0.5804,  0.9216,  0.1294,  0.3804,  0.8667,
         0.9294,  0.2118,  0.7961,  0.9529,  0.4314,  0.2980,  0.1922,
         0.4118,  0.1804,  0.3922,  0.6235,  0.6275,  0.8431,  0.1176,
         0.7608,  0.8157,  0.5333,  0.9137,  0.2392,  0.1725,  0.8039,
         0.3882,  0.9294,  0.1059,  0.0745,  0.4392,  0.9961,  0.2980,
         0.0627,  0.6275,  0.0000,  0.9961,  0.5098,  0.2588,  0.2902,
         0.9686,  0.7451,  0.7961,  0.7961,  0.6706,  0.0588,  0.1647,
         0.6588,  0.3255,  0.1686,  0.7686,  0.1333,  0.4784,  0.1569,
      

In [145]:
import torch as t
import torch

In [102]:
f = nn.Conv2d(3, 1, 2)

In [103]:
f(t.randn(1, 3, 10, 10)).shape

torch.Size([1, 1, 9, 9])

In [106]:
x.resize_(42,8)
x.shape

torch.Size([42, 8])

In [108]:
nn.Linear(10, 10)

Linear(in_features=10, out_features=10, bias=True)

In [138]:
a = t.randn(5,3)
b = t.randn(4, 3)
a,b

(tensor([[ 1.7061,  0.1218, -2.2279],
         [-0.0395,  0.2387,  0.2461],
         [-0.7927, -0.6735, -0.3718],
         [-0.3478,  0.5245, -0.5958],
         [-1.1898, -0.1467, -0.2381]]), tensor([[-0.8228,  0.2954, -0.3622],
         [-0.9790,  0.4025, -0.7653],
         [ 0.2099, -1.8824, -0.1606],
         [ 1.6328,  0.7243,  0.5299]]))

In [141]:
a.unsqueeze(0).shape

torch.Size([1, 5, 3])

tensor([[ 1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.]])

In [146]:
def compute_kernel(x, y):
    x_size = x.size(0)
    y_size = y.size(0)
    dim = x.size(1)
    x = x.unsqueeze(1) # (x_size, 1, dim)
    y = y.unsqueeze(0) # (1, y_size, dim)
    tiled_x = x.expand(x_size, y_size, dim)
    tiled_y = y.expand(x_size, y_size, dim)
    kernel_input = (tiled_x - tiled_y).pow(2).mean(2)/float(dim)
    return torch.exp(-kernel_input) # (x_size, y_size)

def compute_mmd(x, y):
    x_kernel = compute_kernel(x, x)
    y_kernel = compute_kernel(y, y)
    xy_kernel = compute_kernel(x, y)
    mmd = x_kernel.mean() + y_kernel.mean() - 2*xy_kernel.mean()
    return mmd

In [147]:
z1, z2 = t.randn(2, 10, 10)

In [148]:
compute_mmd(z1, z2)

tensor(1.00000e-02 *
       3.0256)

In [153]:
  def kernel(a, b):
    N_a, D = a.size()
    N_b = b.size(0)

    a = a.unsqueeze(1).expand(N_a, N_b, D)
    b = b.unsqueeze(0).expand(N_a, N_b, D)

    return a.sub(b).pow_(2).mean(dim=2).div_(D).mul_(-1).exp_()

  def mmd_loss(y_prd, y):
    y_prd_k = kernel(y_prd, y_prd)
    y_k = kernel(y, y)
    y_prd_y_k = kernel(y_prd, y)

    # return y_k.mean() + y_prd_k.mean() - 2*y_prd_y_k.mean()
    return y_prd_y_k.mul(-2).add_(y_prd_k).add_(y_k).mean()

In [154]:
mmd_loss(z1, z2)

tensor(1.00000e-02 *
       3.0256)